### ISSUE TITLE
path problems with `new PubApp.global(...)`

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#172]
```dart
lint() => new PubApp.global('linter').run(['--stats', '-c tool/lintcfg.yaml', '.']);
```
fails
```
$ grind lint
grinder running [lint]

[lint]
  pub global list
  pub global run linter --stats -c tool/lintcfg.yaml .
  Unhandled exception:
  FileSystemException: Cannot open file, path = ' tool/lintcfg.yaml' (OS Error: No such file or directory, errno = 2)
  #0      _File.throwIfError (dart:io/file_impl.dart:556)
  #1      _File.openSync (dart:io/file_impl.dart:408)
  #2      _File.readAsBytesSync (dart:io/file_impl.dart:467)
  #3      _File.readAsStringSync (dart:io/file_impl.dart:501)
  #4      readFile (package:linter/src/io.dart:70)
  #5      runLinter (http://localhost:48028/linter.dart:87)
  #6      main (http://localhost:48028/linter.dart:15)
  #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
  #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

pub failed with:
exit code: 255

stdout:



stderr:

Unhandled exception:
FileSystemException: Cannot open file, path = ' tool/lintcfg.yaml' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:556)
#1      _File.openSync (dart:io/file_impl.dart:408)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:467)
#3      _File.readAsStringSync (dart:io/file_impl.dart:501)
#4      readFile (package:linter/src/io.dart:70)
#5      runLinter (http://localhost:48028/linter.dart:87)
#6      main (http://localhost:48028/linter.dart:15)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      run (package:grinder/src/run.dart:41:5)
#1      PubGlobal.run (package:grinder/grinder_tools.dart:219:12)
#2      _PubGlobalApp.run (package:grinder/grinder_tools.dart:302:23)
#3      lint (file:///home/myuser/dart/bwu_datagrid/tool/grind.dart:41:39)
#4      _LocalLibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1293)
#5      _LocalObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:372)
#6      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:80:38)
#7      _rootRun (dart:async/zone.dart:895)
#8      _CustomZone.run (dart:async/zone.dart:796)
#9      runZoned (dart:async/zone.dart:1251)
#10     ZonedValue.withValue (package:grinder/src/utils.dart:115:12)
#11     GrinderTask.execute (package:grinder/grinder.dart:176:27)
#12     Grinder._executeTask (package:grinder/grinder.dart:383:23)
#13     Grinder.start.<anon> (package:grinder/grinder.dart:358:16)
#14     Future.forEach.<anon>.<anon> (dart:async/future.dart:336)
#15     Future.Future.sync (dart:async/future.dart:168)
#16     Future.forEach.<anon> (dart:async/future.dart:336)
#17     Future.Future.sync (dart:async/future.dart:168)
#18     Future.doWhile.<anon> (dart:async/future.dart:361)
#19     StackZoneSpecification.registerUnaryCallback.<anon>.<anon> (package:stack_trace/src/stack_zone_specification.dart:134:26)
#20     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:210:15)
#21     StackZoneSpecification.registerUnaryCallback.<anon> (package:stack_trace/src/stack_zone_specification.dart:134:14)
#22     _rootRunUnary (dart:async/zone.dart:902)
#23     _CustomZone.runUnary (dart:async/zone.dart:804)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
#25     _CustomZone.bindUnaryCallback.<anon> (dart:async/zone.dart:738)
#26     Future.doWhile (dart:async/future.dart:367)
#27     Future.forEach (dart:async/future.dart:334)
#28     Grinder.start (package:grinder/grinder.dart:357:21)
#29     handleArgs (package:grinder/src/cli.dart:54:29)
#30     grind.<anon> (package:grinder/grinder.dart:65:10)
#31     Future.Future.<anon> (dart:async/future.dart:118)
#32     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:210:15)
#33     StackZoneSpecification.registerCallback.<anon> (package:stack_trace/src/stack_zone_specification.dart:124:48)
#34     _rootRun (dart:async/zone.dart:891)
#35     _CustomZone.run (dart:async/zone.dart:796)
#36     _CustomZone.runGuarded (dart:async/zone.dart:704)
#37     _CustomZone.bindCallback.<anon> (dart:async/zone.dart:729)
#38     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:210:15)
#39     StackZoneSpecification.registerCallback.<anon> (package:stack_trace/src/stack_zone_specification.dart:124:48)
```
but
```bash
pub global run linter --stats -c tool/lintcfg.yaml .
```
works fine (both from within my package directory)

**Comment by zoechi** [comment]
I just found out that it works when I remove the space between `-c` and `tool/lintcfg.yaml`:
```dart
lint() => new PubApp.global('linter').run(['--stats', '-ctool/lintcfg.yaml', '.']);
```

**Comment by zoechi** [comment]
```dart
lint() => new PubApp.global('linter').run(['--stats', '-c', 'tool/lintcfg.yaml', '.']);
```
works as well. 
If this is a bug at all it's very probably not a Grider bug.
