### ISSUE TITLE
Better error handling when invoked with unknown task name

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#219]
```
 (master) $ grind format
Unhandled exception:
Uncaught Error: GrinderException: task 'format' doesn't exist
Stack Trace:
#0      Grinder.start (package:grinder/grinder.dart:321:9)
#1      handleArgs (package:grinder/src/cli.dart:54:29)
#2      grind.<anonymous closure> (package:grinder/grinder.dart:71:10)
#3      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
IMHO it should just print the usage information like when invoked like `grind -h`.

**Comment by devoncarew** [comment]
Confirmed - I think we regressed here.

**Comment by seaneagan** [comment]
Need to add handling for that in the CLI code, similar to what we do when there is no default task and no specified task to run:

https://github.com/google/grinder.dart/blob/master/lib/src/cli.dart#L64

**Comment by devoncarew** [comment]
Fixed - we now say `Error, no task found: 'foobar'.`
