### ISSUE TITLE
Checked mode error in grind script

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#222]
I tried to debug my grinder script but when I don't start it with `grind task` but instead with
`dart -c tool/grind.dart task`

I get 

```
Unhandled exception:
Uncaught Error: Failed assertion: boolean expression must not be null
Stack Trace:
#0      cli (package:grinder/src/cli.dart:47:7)
#1      Function._apply (dart:core-patch/function_patch.dart:7)
#2      Function.apply (dart:core-patch/function_patch.dart:28)
#3      FunctionScript._getTopCommandResult (package:unscripted/src/script_impl.dart:154:67)
#4      DeclarationScript._handleResults (package:unscripted/src/script_impl.dart:104:21)
#5      ScriptImpl.execute.<anonymous closure>.<anonymous closure> (package:unscripted/src/script_impl.dart:49:11)
#6      _RootZone.runUnary (dart:async/zone.dart:1166)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#9      _Future._completeWithValue (dart:async/future_impl.dart:368)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#12     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Process finished with exit code 255
```

**Comment by seaneagan** [comment]
It's a checked mode error.  I guess we should be running the script in checked mode in CI at least, but it's nice to use `pub run grinder` instead of `dart tool/grind.dart` to set a good example for other projects, since `pub run` is required if you want to run any transformers.  I think running pub scripts from checked mode is blocked by http://dartbug.com/21791.

**Comment by devoncarew** [comment]
+1 to running in checked mode when running our tests / buildbot script.

`pub run grinder` is simpler, however I also want to preserve the ability to just run a bare script (`dart tool/grind.dart`).
