### ISSUE TITLE
Request: optionally silence the stack trace on fail(msg)

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#288]
I'm told that `fail(msg)` is the way to go, when my task wants to tell the user something and stop executing.

However, fail is very verbose. Can I fail, print a message, but not print the stack trace?

Currently, I see:

```
~/Code/dartdoc[global-install*] $ grind publish
grinder running [publish]

[publish]

finished in 0.028 seconds.
  failed: ERROR: CHANGELOG.md does not contain mention of version 0.1.0+4
Unhandled exception:
Uncaught Error: GrinderException: ERROR: CHANGELOG.md does not contain mention of version 0.1.0+4
Stack Trace:
#0      GrinderContext.fail (package:grinder/grinder.dart:148:5)
#1      fail (package:grinder/grinder.dart:103:38)
#2      publish.<publish_async_body> (file:///Users/sethladd/Code/dartdoc/tool/grind.dart:86:5)
#3      _rootRunUnary (dart:async/zone.dart:911)
#4      _CustomZone.runUnary (dart:async/zone.dart:811)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#7      _Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:560)
#8      _rootRunUnary (dart:async/zone.dart:911)
#9      _CustomZone.runUnary (dart:async/zone.dart:811)
#10     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#11     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#12     _Future._completeWithValue (dart:async/future_impl.dart:368)
#13     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#14     _rootRun (dart:async/zone.dart:904)
#15     _CustomZone.run (dart:async/zone.dart:803)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:736)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#18     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

which is way too much.

**Comment by seaneagan** [comment]
Once we fix #146, the stack traces should be quite short, at which this may no longer be an issue?

**Comment by sethladd** [comment]
I don't think the user will care about a stacktrace in my case. But maybe I shouldn't be using fail() ?

**Comment by devoncarew** [comment]
It's like to at least have the file and line where `fail()` was called, and perhaps a bit more for context.

**Comment by devoncarew** [comment]
fixed in the upcoming dev release
