### ISSUE TITLE
Bad state: StreamSink is bound to a stream

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#291]
For dartdoc, I have two tasks, one depends on the other (validate-sdk-docs depends on build-sdk-docs).

If I run:

grind build-sdk-docs
grind validate-sdk-docs

Then it works.

But if I run grind validate-sdk-docs (which tries to run build-sdk-docs first), I get this error:

```
Uncaught Error: Bad state: StreamSink is bound to a stream
Stack Trace:
#0      _StreamSinkImpl._controller (dart:io/io_sink.dart:220)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:143)
#2      _IOSinkImpl.write (dart:io/io_sink.dart:278)
#3      _IOSinkImpl.writeln (dart:io/io_sink.dart:298)
#4      _StdSink.writeln (dart:io/stdio.dart:258)
#5      _NoopContext.fail (package:grinder/src/singleton.dart:21:12)
#6      fail (package:grinder/grinder.dart:103:38)
#7      cli.<anonymous closure> (package:grinder/src/cli.dart:76:7)
#8      _RootZone.runBinary (dart:async/zone.dart:1171)
#9      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:521)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:580)
#11     _Future._completeError (dart:async/future_impl.dart:376)
#12     _RootZone.runBinary (dart:async/zone.dart:1171)
#13     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:521)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:580)
#15     _Future._completeError (dart:async/future_impl.dart:376)
#16     _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:431)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#18     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-lang/dartdoc/pull/1242; this was an issue w/ how the task was using await
