### ISSUE TITLE
Grinder can't find Dart executable on Dart 2.13.1 / Flutter 2.2.1

### ISSUE THREAD

**Issue by domesticmouse** [google/grinder.dart#379]
Failing [build log](https://github.com/dart-lang/dart-services/pull/721/checks?check_run_id=2689821886#step:9:327):

```console
  failed: Unable to exec dart, failed with code 2
GrinderException: Unable to exec dart, failed with code 2
#0      GrinderContext.fail (package:grinder/src/grinder_context.dart:42:5)
#1      fail (package:grinder/src/grinder_context.dart:59:39)
#2      runWithLogging (file:///home/runner/work/dart-services/dart-services/tool/grind.dart:410:5)
<asynchronous suspension>
#3      analyze (file:///home/runner/work/dart-services/dart-services/tool/grind.dart:30:3)
<asynchronous suspension>
#4      _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart)
<asynchronous suspension>
```

The failing function at the bottom of this stack trace is this one:

```dart
Future<void> runWithLogging(String executable,
    {List<String> arguments = const [],
    RunOptions runOptions,
    String workingDirectory,
    String onErrorMessage}) async {
  runOptions = mergeWorkingDirectory(workingDirectory, runOptions);
  log("$executable ${arguments.join(' ')}");
  runOptions ??= RunOptions();

  Process proc;
  try {
    proc = await Process.start(executable, arguments,
        workingDirectory: runOptions.workingDirectory,
        environment: runOptions.environment,
        includeParentEnvironment: runOptions.includeParentEnvironment,
        runInShell: runOptions.runInShell);
  } catch (e) {
    if (onErrorMessage != null) {
      print(onErrorMessage);
    }
    rethrow;
  }

  proc.stdout.listen((out) => log(runOptions.stdoutEncoding.decode(out)));
  proc.stderr.listen((err) => log(runOptions.stdoutEncoding.decode(err)));
  final exitCode = await proc.exitCode;

  if (exitCode != 0) {
    fail('Unable to exec $executable, failed with code $exitCode');
  }
}
```

**Comment by domesticmouse** [comment]
Actually I can't read
