### ISSUE TITLE
ProcessException: No such file or directory

### ISSUE THREAD

**Issue by komritza** [google/grinder.dart#384]
When running `grind format` I am getting following error in console:
```
format
  /usr/local/Cellar/dart/2.16.1/libexec/bin/dart format -w --fix .

ProcessException: No such file or directory
  Command: /usr/local/Cellar/dart/2.16.1/libexec/bin/dart format -w --fix .
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      run (package:grinder/src/run.dart:28:26)
#4      format (file:///Users/<user>/Documents/flutter-projects/application/<appname>/business_logic/tool/grind.dart:37:18)
#5      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:999:68)
#6      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:248:25)
#7      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:78:38)
#8      _rootRun (dart:async/zone.dart:1426:13)
#9      _CustomZone.run (dart:async/zone.dart:1328:19)
#10     _runZoned (dart:async/zone.dart:1861:10)
#11     runZoned (dart:async/zone.dart:1783:10)
#12     ZonedValue.withValue (package:grinder/src/utils.dart:113:12)
#13     GrinderTask.execute (package:grinder/src/grinder_task.dart:65:27)
#14     Grinder._invokeTask (package:grinder/src/grinder.dart:213:27)
#15     Grinder.start.<anon> (package:grinder/src/grinder.dart:174:16)
#16     Future.forEach.<anon> (dart:async/future.dart:573:26)
#17     Future.doWhile.<anon> (dart:async/future.dart:613:26)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#19     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1657:26)
#20     Future.doWhile (dart:async/future.dart:629:18)
#21     Future.forEach (dart:async/future.dart:571:12)
#22     Grinder.start (package:grinder/src/grinder.dart:173:21)
#23     runTasks (package:grinder/src/cli.dart:69:38)
#24     grind (package:grinder/grinder.dart:45:12)
#25     main (file:///Users/<user>/Documents/flutter-projects/application/<appname>/business_logic/tool/grind.dart:9:3)
```
When running `dart format .` or `dart format --fix .`  it is working without any issues, files are formatted correctly. 

Running `grind test` is working without any issues.

`grind.dart` file: 
```dart
import 'dart:io';

import 'package:grinder/grinder.dart';

void main([List<String>? args]) {
  grind(args ?? []);
}

@Task('Format source code')
void format() => run(sdkBin('dart format'), arguments: ['-w', '--fix', '.']);

@Task('Run test')
void test() => Pub.run('test');

```

`flutter doctor -v` 
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-x64, locale de-AT)
    • Flutter version 2.8.1 at /Users/markoabacus/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/markoabacus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.80

• No issues found!
```

Any tips how to solve this?

**Comment by komritza** [comment]
Found the fix
```
void format() => run(sdkBin('dart'), arguments: ['format', '--fix', '.']);
```
